### ISSUE TITLE
objectwalker failed to run

### ISSUE THREAD

**Issue by schmandforke** [pemcg/object_walker#3]
Hey, 

i just want to report that the objectwalker 1.7 isn't running in Capablanca anymore, got the following exception:

```
[----] E, [2016-05-27T15:21:48.736815 #23711:82f2670] ERROR -- : Q-task_id([miq_provision_5000000000032]) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:116:in `const_get'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:116:in `block in wrap_results'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:261:in `ar_method'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:108:in `wrap_results'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:112:in `block (2 levels) in wrap_results'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:112:in `collect'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:112:in `block in wrap_results'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:261:in `ar_method'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:108:in `wrap_results'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:126:in `wrap_results'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:97:in `block (2 levels) in expose'
/opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1624:in `perform_without_block'
/opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1584:in `perform'
/opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1657:in `block (2 levels) in main_loop'
/opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1653:in `loop'
/opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1653:in `block in main_loop'
[----] E, [2016-05-27T15:21:48.736984 #23711:82f2670] ERROR -- : Q-task_id([miq_provision_5000000000032]) MiqAeServiceModelBase.ar_method raised: <NameError>: <uninitialized constant MiqAeMethodService::MiqAeServiceMiqAeDomain>
[----] E, [2016-05-27T15:21:48.737159 #23711:82f2670] ERROR -- : Q-task_id([miq_provision_5000000000032]) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:116:in `const_get'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:116:in `block in wrap_results'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:261:in `ar_method'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:108:in `wrap_results'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:112:in `block (2 levels) in wrap_results'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:112:in `collect'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:112:in `block in wrap_results'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:261:in `ar_method'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:108:in `wrap_results'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:126:in `wrap_results'
/var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:97:in `block (2 levels) in expose'
/opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1624:in `perform_without_block'
/opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1584:in `perform'
/opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1657:in `block (2 levels) in main_loop'
/opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1653:in `loop'
/opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1653:in `block in main_loop'
[----] E, [2016-05-27T15:21:48.740067 #23711:267a370] ERROR -- : Q-task_id([miq_provision_5000000000032]) <AEMethod objectwalker> object_walker#96551C21 (dump_associations) - [uninitialized constant MiqAeMethodService::MiqAeServiceMiqAeDomain]
(druby://127.0.0.1:37446) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:116:in `const_get'
(druby://127.0.0.1:37446) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:116:in `block in wrap_results'
(druby://127.0.0.1:37446) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:261:in `ar_method'
(druby://127.0.0.1:37446) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:108:in `wrap_results'
(druby://127.0.0.1:37446) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:112:in `block (2 levels) in wrap_results'
(druby://127.0.0.1:37446) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:112:in `collect'
(druby://127.0.0.1:37446) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:112:in `block in wrap_results'
(druby://127.0.0.1:37446) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:261:in `ar_method'
(druby://127.0.0.1:37446) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:108:in `wrap_results'
(druby://127.0.0.1:37446) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:126:in `wrap_results'
(druby://127.0.0.1:37446) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:97:in `block (2 levels) in expose'
(druby://127.0.0.1:37446) /opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1624:in `perform_without_block'
(druby://127.0.0.1:37446) /opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1584:in `perform'
(druby://127.0.0.1:37446) /opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1657:in `block (2 levels) in main_loop'
(druby://127.0.0.1:37446) /opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1653:in `loop'
(druby://127.0.0.1:37446) /opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/drb/drb.rb:1653:in `block in main_loop'
<code: associated_objects = Array.wrap(this_object.send(association))>:596:in `block in dump_associations'
<code: object_associations.uniq.sort.each do |association|>:594:in `each'
<code: object_associations.uniq.sort.each do |association|>:594:in `dump_associations'
<code: dump_associations(object_string, this_object, this_object_class)>:789:in `dump_object'
<code: dump_object("#{object_string}[\'#{attribute_name}\']", attribute_value)>:377:in `block in dump_attributes'
<code: this_object.attributes.keys.sort.each do |attribute_name|>:370:in `each'
<code: this_object.attributes.keys.sort.each do |attribute_name|>:370:in `dump_attributes'
<code: dump_attributes(object_string, this_object)>:787:in `dump_object'
<code: dump_object("$evm.root", $evm.root)>:876:in `<main>'
```

**Comment by pemcg** [comment]
Hi, thanks for bringing this to my attention.

What you're seeing is object_walker discovering a bug in ManageIQ (https://bugzilla.redhat.com/show_bug.cgi?id=1287473), when it tried to walk a broken association. If you use the object_walker_reader you should see that it recovered from the exception and continued to walk/print the remaining objects. If this didn't happen then would you be able to send me your automation.log file for me to take a look at?

I'm open to suggestions if you think that the exception handling could do things differently.

Many thanks,
Peter
